name: Bump Version

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "wiki/**"
      - "**/*.md"
      - ".github/workflows/**"
  workflow_dispatch: {}

jobs:
  bump:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency: bump

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create tag
        id: bump
        run: |
          cz bump --yes --changelog
          echo "version=$(cz version --project)" >> $GITHUB_OUTPUT

      - name: Push changes and tags
        run: |
          git push origin master --follow-tags
