name: Tag Bump Release

on:
  push:
    branches: [ "master" ]

jobs:
  tag:
    # Only run when the commit message is the bump commit from the PR
    if: startsWith(github.event.head_commit.message, 'bump:')
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to push tags

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Commitizen
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Read version and create tag
        run: |
          VERSION="$(cz version --project)"
          echo "Version resolved to: $VERSION"
          # Create lightweight tag without 'v' prefix to match your existing style (e.g., 0.155.0)
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"
